version: 0.0
os: linux
files:
  - source: first.txt
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: httpd_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: httpd_start.sh
      timeout: 300
      runas: root
