version: 0.0
os: linux
files:
  - source: /first.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: httpd_stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: httpd_start.sh
      timeout: 300
      runas: ubuntu
